name: conform
channels:
  - defaults
dependencies:
  - python
  - torchaudio
  - torchvision
  - pytorch
  - pytorch-cuda=12.1
  - jupyter
  - diffusers==0.21.4
  - conda-forge::transformers
  - pytorch-metric-learning
